name = "TropicalNumbers"
uuid = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"
authors = ["GiggleLiu"]
version = "0.2.2"

[compat]
julia = "1.0,1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
